import { Form7501Result } from "./form7501";

/**
 * Clean, zero-dependency server-side PDF renderer for CBP Form 7501 (Entry Summary).
 * Constructs a valid %PDF-1.4 binary stream containing formatted tables, boxes,
 * and entry summary details.
 */
export function generateForm7501PdfBuffer(form: Form7501Result): Buffer {
  const sanitize = (text?: string | number | null) => {
    if (text === null || text === undefined) return "-";
    return String(text).replace(/[()\\]/g, "");
  };

  const entryNo = sanitize(form.entryNumber.value);
  const entryType = sanitize(form.entryType.value);
  const importer = sanitize(form.importerName.value);
  const importerNum = sanitize(form.importerNumber.value);
  const port = sanitize(form.portCode.value);
  const bond = sanitize(form.bondNumber.value);
  const exportCountry = sanitize(form.countryOfExport.value);
  const carrier = sanitize(form.carrier.value);
  const totalValue = form.totalEnteredValue.value !== null ? `$${form.totalEnteredValue.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "$0.00";
  const totalDuty = form.totalDuty.value !== null ? `$${form.totalDuty.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "$0.00";

  const linesStreamCommands: string[] = [];
  let y = 520;
  
  for (const item of form.lineItems) {
    if (y < 120) break; // page limit for single page summary stub
    const lineNo = sanitize(item.lineNumber);
    const desc = sanitize(item.description.value).substring(0, 32);
    const hts = sanitize(item.htsCode.value);
    const country = sanitize(item.countryOfOrigin.value);
    const qty = item.quantity.value !== null ? String(item.quantity.value) : "1";
    const val = item.enteredValue.value !== null ? `$${item.enteredValue.value.toFixed(2)}` : "$0.00";
    const rate = item.dutyRate.value !== null ? `${(item.dutyRate.value * 100).toFixed(2)}%` : "0.00%";
    const duty = item.dutyAmount.value !== null ? `$${item.dutyAmount.value.toFixed(2)}` : "$0.00";

    linesStreamCommands.push(
      `BT /F2 8 Tf 45 ${y} Td (${lineNo}) Tj 75 ${y} Td (${desc}) Tj 215 ${y} Td (${hts}) Tj 305 ${y} Td (${country}) Tj 345 ${y} Td (${qty}) Tj 400 ${y} Td (${val}) Tj 460 ${y} Td (${rate}) Tj 525 ${y} Td (${duty}) Tj ET`
    );
    y -= 18;
  }

  const streamContent = [
    "q",
    "0.2 0.4 0.8 rg 40 730 532 50 re f",
    "1 1 1 rg BT /F1 16 Tf 55 750 Td (DEPARTMENT OF HOMELAND SECURITY - CBP) Tj ET",
    "1 1 1 rg BT /F1 12 Tf 360 750 Td (CBP FORM 7501) Tj ET",
    "1 1 1 rg BT /F2 10 Tf 360 736 Td (ENTRY SUMMARY) Tj ET",
    "0 0 0 rg",
    "40 720 532 1 re s",
    // Header Grid Box
    "40 600 532 110 re s",
    "40 680 532 1 re s",
    "40 640 532 1 re s",
    "180 600 1 110 re s",
    "350 600 1 110 re s",
    // Field Labels and Values
    `BT /F1 8 Tf 45 695 Td (1. ENTRY TYPE: ${entryType}) Tj ET`,
    `BT /F1 8 Tf 185 695 Td (2. ENTRY NUMBER: ${entryNo}) Tj ET`,
    `BT /F1 8 Tf 355 695 Td (4. BOND NUMBER: ${bond}) Tj ET`,
    `BT /F1 8 Tf 45 655 Td (8. CARRIER: ${carrier}) Tj ET`,
    `BT /F1 8 Tf 185 655 Td (10. COUNTRY OF EXPORT: ${exportCountry}) Tj ET`,
    `BT /F1 8 Tf 355 655 Td (45. PORT OF ENTRY: ${port}) Tj ET`,
    `BT /F1 8 Tf 45 615 Td (23. IMPORTER NO: ${importerNum}) Tj ET`,
    `BT /F1 8 Tf 185 615 Td (25. IMPORTER OF RECORD: ${importer}) Tj ET`,
    `BT /F1 8 Tf 355 615 Td (TOTAL ENTERED VALUE: ${totalValue}) Tj ET`,
    // Table Header Line
    "0.9 0.9 0.9 rg 40 540 532 20 re f 0 0 0 rg",
    "40 540 532 20 re s",
    "BT /F1 8 Tf 45 546 Td (LN) Tj 75 546 Td (DESCRIPTION) Tj 215 546 Td (HTS CODE) Tj 305 546 Td (COO) Tj 345 546 Td (QTY) Tj 400 546 Td (VALUE) Tj 460 546 Td (RATE) Tj 525 546 Td (DUTY) Tj ET",
    // Line Items
    ...linesStreamCommands,
    // Summary Footer Box
    "0.95 0.95 0.95 rg 40 60 532 40 re f 0 0 0 rg",
    "40 60 532 40 re s",
    `BT /F1 10 Tf 50 82 Td (TOTAL CUSTOMS VALUE: ${totalValue}) Tj ET`,
    `BT /F1 10 Tf 300 82 Td (TOTAL DUTIES & FEES: ${totalDuty}) Tj ET`,
    `BT /F2 8 Tf 50 68 Td (Generated by Qubere Trade Engine & CBP Automated Commercial Environment) Tj ET`,
    "Q",
  ].join("\n");

  const streamLength = Buffer.byteLength(streamContent);

  const pdfParts: string[] = [
    "%PDF-1.4\n",
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n",
    "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources 4 0 R /Contents 5 0 R >>\nendobj\n",
    "4 0 obj\n<< /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >>\nendobj\n",
    `5 0 obj\n<< /Length ${streamLength} >>\nstream\n${streamContent}\nendstream\nendobj\n`,
  ];

  // Calculate cross reference offsets
  let offset = 0;
  const offsets: number[] = [0];
  for (let i = 0; i < pdfParts.length; i++) {
    offsets.push(offset + pdfParts[i].length);
    offset += pdfParts[i].length;
  }

  const xrefOffset = offset;
  let xref = `xref\n0 6\n0000000000 65535 f \n`;
  let currentOffset = pdfParts[0].length;
  for (let i = 1; i <= 5; i++) {
    xref += `${String(currentOffset).padStart(10, "0")} 00000 n \n`;
    currentOffset += pdfParts[i].length;
  }

  const trailer = `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  const fullPdfString = pdfParts.join("") + xref + trailer;
  return Buffer.from(fullPdfString, "binary");
}
