export enum AuditAction {
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_CLASSIFIED = "DOCUMENT_CLASSIFIED",
  FIELD_CORRECTED = "FIELD_CORRECTED",
  DECISION_AUTO_APPROVED = "DECISION_AUTO_APPROVED",
  DECISION_APPROVED = "DECISION_APPROVED",
  DECISION_REJECTED = "DECISION_REJECTED",
  DECISION_OVERRIDDEN = "DECISION_OVERRIDDEN",
  EXCEPTION_RESOLVED = "EXCEPTION_RESOLVED",
  EXCEPTION_WAIVED = "EXCEPTION_WAIVED",
  FILING_SUBMITTED = "FILING_SUBMITTED",
  CLASSIFICATION_CHANGED = "CLASSIFICATION_CHANGED",
}
