export enum AuditAction {
  // Document Operations
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_CLASSIFIED = "DOCUMENT_CLASSIFIED",
  DOCUMENT_REPROCESSED = "DOCUMENT_REPROCESSED",
  DOCUMENT_DELETED = "DOCUMENT_DELETED",
  DOCUMENT_STORED = "DOCUMENT_STORED",
  DOCUMENT_QUEUED = "DOCUMENT_QUEUED",
  FIELD_CORRECTED = "FIELD_CORRECTED",
  CLASSIFICATION_CHANGED = "CLASSIFICATION_CHANGED",

  // Decision & Exception Operations
  DECISION_APPROVED = "DECISION_APPROVED",
  DECISION_REJECTED = "DECISION_REJECTED",
  DECISION_AUTO_APPROVED = "DECISION_AUTO_APPROVED",
  DECISION_OVERRIDDEN = "DECISION_OVERRIDDEN",
  EXCEPTION_CREATED = "EXCEPTION_CREATED",
  EXCEPTION_RESOLVED = "EXCEPTION_RESOLVED",
  EXCEPTION_WAIVED = "EXCEPTION_WAIVED",
  EXCEPTION_ASSIGNED = "EXCEPTION_ASSIGNED",

  // Filing Operations
  FILING_CREATED = "FILING_CREATED",
  FILING_SUBMITTED = "FILING_SUBMITTED",
  FILING_APPROVED = "FILING_APPROVED",
  FILING_TRANSMITTED = "FILING_TRANSMITTED",
  FILING_CANCELLED = "FILING_CANCELLED",
  FILING_RESUBMITTED = "FILING_RESUBMITTED",
  FILING_UPDATED = "FILING_UPDATED",
  FILING_VALIDATED = "FILING_VALIDATED",

  // Product Master Operations
  PRODUCT_CREATED = "PRODUCT_CREATED",
  PRODUCT_UPDATED = "PRODUCT_UPDATED",
  PRODUCT_ARCHIVED = "PRODUCT_ARCHIVED",
  PRODUCT_IMPORTED = "PRODUCT_IMPORTED",
  PRODUCT_CLASSIFIED = "PRODUCT_CLASSIFIED",
  PRODUCT_LINE_ATTACHED = "PRODUCT_LINE_ATTACHED",

  // Party Master Operations
  PARTY_CREATED = "PARTY_CREATED",
  PARTY_UPDATED = "PARTY_UPDATED",
  PARTY_ARCHIVED = "PARTY_ARCHIVED",
  PARTY_IMPORTED = "PARTY_IMPORTED",
  PARTY_SCREENED = "PARTY_SCREENED",
  PARTY_CONTACT_ADDED = "PARTY_CONTACT_ADDED",
  PARTY_CONTACT_REMOVED = "PARTY_CONTACT_REMOVED",
  PARTY_SITE_ADDED = "PARTY_SITE_ADDED",
  PARTY_SITE_REMOVED = "PARTY_SITE_REMOVED",

  // Advisory, Audit & Compliance
  ORIGIN_DETERMINED = "ORIGIN_DETERMINED",
  COMPLIANCE_AUDIT_RUN = "COMPLIANCE_AUDIT_RUN",
  REASONABLE_CARE_GENERATED = "REASONABLE_CARE_GENERATED",
  FOCUSED_ASSESSMENT_GENERATED = "FOCUSED_ASSESSMENT_GENERATED",
  ADVISORY_QUERIED = "ADVISORY_QUERIED",

  // Refunds & PSC
  REFUND_PSC_CREATED = "REFUND_PSC_CREATED",
  REFUND_PSC_UPDATED = "REFUND_PSC_UPDATED",
  DRAWBACK_CLAIM_CREATED = "DRAWBACK_CLAIM_CREATED",
  DRAWBACK_CLAIM_SUBMITTED = "DRAWBACK_CLAIM_SUBMITTED",

  // Intake & System Operations
  INTAKE_SHIPMENT_CREATED = "INTAKE_SHIPMENT_CREATED",
  REGULATORY_RULING_INGESTED = "REGULATORY_RULING_INGESTED",
  AGENT_EXECUTION_COMPLETED = "AGENT_EXECUTION_COMPLETED",
  CLASSIFICATION_CASE_CREATED = "CLASSIFICATION_CASE_CREATED",
  CLASSIFICATION_CASE_DECIDED = "CLASSIFICATION_CASE_DECIDED",
}

