-- AlterEnum
ALTER TYPE "BillingEventCategory" ADD VALUE 'ORIGIN_DETERMINATION';
ALTER TYPE "BillingEventCategory" ADD VALUE 'VALUATION';
ALTER TYPE "BillingEventCategory" ADD VALUE 'COMPLIANCE_REVIEW';
ALTER TYPE "BillingEventCategory" ADD VALUE 'FILING_READINESS';
